- name: "Add application env variables to .bashrc"
  shell: |
    echo $ENVIRONMENT >> .bashrc
    echo $TYPEORM_CONNECTION >> .bashrc
    echo $TYPEORM_ENTITIES >> .bashrc
    echo $TYPEORM_HOST >> .bashrc
    echo $TYPEORM_PORT >> .bashrc
    echo $TYPEORM_USERNAME >> .bashrc
    echo $TYPEORM_PASSWORD >> .bashrc
    echo $TYPEORM_DATABASE >> .bashrc

- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: 
      - nodejs
    state: latest
    
- name: "Install npm"
  become: yes
  apt:
    name: 
      - npm
    state: latest

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
