- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install zip to uncompress backend source"
  become: yes
  apt:
    name:
      - zip
    state: latest

- name: "Copy backend source to EC2 instance and uncompress"
  unarchive:
    src: ~/backend.zip
    dest: ~/

- name: "Run backend"
  shell: |
    cd ~/backend
    pm2 start npm --name backend -- start
    pm2 ls

#- name: "Copy build to EC2 instance and uncompress"
#  unarchive:
#    src: ~/dist.zip
#    dest: ~/
