- name: "Install zip to uncompress backend source"
  become: yes
  apt:
    name:
      - zip
    state: latest

- name: "Copy build to EC2 instance and uncompress"
  copy:
    src: ~/dist.zip
    dest: ~/

- name: "Backup dist"
  copy:
    src: ~/dist.zip
    dest: ~/dist_backup.zip
    remote_src: yes

# - name: "Copy backend source to EC2 instance and uncompress"
#  unarchive:
#    src: ~/backend.zip
#    dest: ~/

#- name: "Run backend"
#  shell: |
#    cd ~/backend
#    pm2 start npm --name backend -- start
#    pm2 ls

