- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "zip"]
    update_cache: yes

- name: "Downgrade node to 13.8.0 so this POS code can run"
  become: true
  shell: |
    npm install -g n
    n 13.8.0

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy backend source and uncompress"
  unarchive:
    src: ~/project/backend.zip
    dest: ~/

- name: "Build the backend"
  shell: |
    cd backend
    npm i
    npm run build

- name: "Start server"
  shell: |
    cd backend
    npm run start
